### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by b5710546291** [AppsFlyerSDK/appsflyer-flutter-plugin#37]
The following error occurs  when running ios with appsflyer 6.0.2+1. Working fine on 5.4.1+1. 

Failed to build iOS app
Error output from Xcode build:
↳
Could not build the precompiled application for the device.

Error launching application on iPhone.
** BUILD FAILED **

Xcode's output:
↳
/Users/h11e/hmpr/appsflyer-flutter-plugin/example/ios/Runner/AppDelegate.m:4:9: fatal error: 'AppTrackingTransparency/AppTrackingTransparency.h' file not found
#import <AppTrackingTransparency/AppTrackingTransparency.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by jjsebastianfuertes** [comment]
Same problem with Appsflyer 6.0.2+1 running in iPAD 12.4.8.
Although with iPhone 8 with 14.0. the problem is gone. is there any solution for older iOS versions?

**Comment by af-fess** [comment]
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/CHANGELOG.md#6032
